################################# Splunk forwarder #################################
splunk_forwarder_index: bro

################################# Splunk server #################################
splunk_server_addr: 10.150.100.102