[splunk]
splunk01 ansible_host=10.150.100.102 ansible_python_interpreter=/usr/bin/python3 timeout=30

[bro]
bro01 ansible_host=10.150.100.102 ansible_python_interpreter=/usr/bin/python3 timeout=30

[docker]
docker01 ansible_host=10.150.100.102 ansible_python_interpreter=/usr/bin/python3 timeout=30

[caldera]
caldera01 ansible_host=10.150.100.102 ansible_python_interpreter=/usr/bin/python3 timeout=30
