####################################################################
# Set hostname
####################################################################
- name: change hostname to {{ hostname }}
  hostname:
    name: "{{ hostname }}"

- name: add myself to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1[ \t]+localhost'
    line: '127.0.0.1 localhost {{ hostname }}'
    state: present

####################################################################
# Slack notification
####################################################################
- name: Send slack notification when done
  slack:
    token: "{{ slack_token }}"
    msg: '{{ ansible_nodename }}:{{ ansible_default_ipv4.address }} - Set hostname to {{ hostname }} - {{ ansible_nodename }}'
    channel: "{{ slack_channel }}"
  when: slack_token != None