####################################################################
# Install sofrware 
####################################################################
- name: Install dependencies for Bro
  package:
    name: '{{ item }}'
    state: latest
  with_items:
    - cmake 
    - make 
    - gcc 
    - g++ 
    - flex 
    - bison 
    - libpcap-dev 
    - libssl-dev 
    - python-dev 
    - swig 
    - zlib1g-dev
    - tcpdump
    - jq

####################################################################
# Download Zeek source code
####################################################################
- name: Stat BRO/Zeek
  stat:
    path: '{{ bro_base }}/bin/bro'
  register: bro_compile

- name: Download Bro/Zeek source code
  git:
    repo: https://github.com/zeek/zeek
    recursive: yes
    dest: '/tmp/bro'
  when: bro_compile.stat.exists == False

####################################################################
# Install/Setup GeoIP
#
# If you see an error message similar to “Bro was not configured for GeoIP support”, 
# then you need to rebuild Bro and make sure it is linked against libmaxminddb. Normally, 
# if libmaxminddb is installed correctly then it should automatically be found when 
# building Bro. If this doesn’t happen, then you may need to specify the path to the 
# libmaxminddb installation (e.g. ./configure --with-geoip=<path>).
#
# https://docs.zeek.org/en/stable/frameworks/geoip.html
####################################################################
- name: Stat GeoIP database
  stat:
    path: '/usr/share/GeoIP/GeoLite2-City.mmdb'
  register: geoip_db
  when: bro_geoip == True

- name: Install libmaxminddb
  package: 
    name: '{{ item }}'
    state: latest
  with_items:
    - libmaxminddb-dev
  when: bro_geoip == True

- name: Download GeoIP database
  unarchive:
    src: '{{ bro_geoip_db_url }}'
    dest: '/usr/share/GeoIP/'
    remote_src: yes
    extra_opts: [--strip-components=1]
  when: geoip_db.stat.exists == False and bro_geoip == True

####################################################################
# Compile BRO/Zeek from source
####################################################################
- name: Debug msg
  debug:
    msg: 'WARNING - Compiling BRO from source can take up to 30mins'
  when: bro_compile.stat.exists == False

- name: Compile BRO/Zeek from source
  shell: '{{ item }}'
  args:
    chdir: '/tmp/bro'
  with_items:
    - './configure --prefix={{ bro_base }}/'
    - 'make'
    - 'make install'
  when: bro_compile.stat.exists == False

- name: Test GeoIP
  shell: './bro -e "print lookup_location(8.8.8.8);"'
  args:
    chdir: '{{ bro_base }}/bin'
  when: bro_geoip == True 

####################################################################
# Create Bro user and set perms
####################################################################
- name: Create Bro user
  user:
    name: '{{ bro_user }}'
    shell: /usr/sbin/nologin
    home: '{{ bro_base }}'

- name: 'setcap cap_net_raw,cap_net_admin=eip {{ bro_base }}/bin/bro'
  capabilities:
    path: '{{ bro_base }}/bin/bro'
    capability: '{{ item }}'
    state: present
  with_items:
    - 'cap_net_raw+eip'
    - 'cap_net_admin+eip'

- name: Enable BRO promiscious interface
  shell: ip link set dev {{ bro_promiscuous_interface }} up
  when: bro_management_interface != bro_promiscuous_interface

- name: Enable BRO promiscious interface on reboot
  cron:
    name: "Enale BRO monitoring interface"
    special_time: reboot
    job: "ip link set dev {{ bro_promiscuous_interface }} up"
  when: bro_management_interface != bro_promiscuous_interface

- name: Set Bro base dir perms
  file:
    path: '{{ bro_base }}'
    owner: '{{ bro_user }}'
    group: '{{ bro_user }}'
    recurse: yes

- name: Add BRO to system-wide $PATH
  copy:
    dest: /etc/profile.d/bro-path.sh
    content: 'PATH=$PATH:{{ bro_base }}/bin'

####################################################################
# Configure Bro
####################################################################
- name: 'Copy BRO configs'
  template:
    src: 'conf/bro/{{ item }}'
    dest: '{{ bro_base }}/etc/{{ item }}'
    owner: '{{ bro_user }}'
    group: '{{ bro_user }}'
  with_items:
    - 'networks.cfg'
    - 'node.cfg'
  
- name: Replace BRO e-mail
  lineinfile:
    path: '{{ bro_base }}/etc/broctl.cfg'
    regexp: '^MailTo ='
    line: 'MailTo = {{ bro_mail_to }}'

- name: Enable Bro logging in JSON format
  lineinfile:
    path: '{{ bro_base }}/share/bro/site/local.bro'
    line: '{{ item }}'
  with_items:
    - '# Enable Bro logging in JSON format'
    - 'redef LogAscii::json_timestamps = JSON::TS_ISO8601;'
    - 'redef LogAscii::use_json = T;'

- name: Create scripts directory for custom BRO scripts
  file:
    path: '{{ bro_base }}/share/bro/scripts'
    state: directory
    owner: '{{ bro_user }}'
    group: '{{ bro_user }}'

####################################################################
# BRO scripts
####################################################################
- name: Enable BRO file extraction
  lineinfile:
    path: '{{ bro_base }}/share/bro/site/local.bro'
    line: '{{ item }}'
  with_items:
    - '# BRO file extraction'
    - '@load policy/frameworks/files/extract-all-files.bro'
  when: bro_file_extraction == True

- name: Enable Bro stats 
  lineinfile:
    path: '{{ bro_base }}/share/bro/site/local.bro'
    line: '{{ item }}'
  with_items:
    - '# BRO stats'
    - '@load policy/misc/stats.bro'
  when: bro_stats == True

- name: Copy custom BRO scripts
  template:
    src: "{{ item }}"
    dest: '{{ bro_base }}/share/bro/scripts/{{ item | basename }}'
    owner: root
    group: bro
  with_fileglob:
    - 'conf/bro/scripts/*'
  when: bro_custom_scripts == True

- name: Add commnet for custom scripts 
  lineinfile:
    path: '{{ bro_base }}/share/bro/site/local.bro'
    line: '# BRO custom scripts'
  when: bro_custom_scripts == True

- name: Enable BRO file extraction
  lineinfile:
    path: '{{ bro_base }}/share/bro/site/local.bro'
    line: '@load scripts/{{ item | basename }}'
  with_fileglob:
    - 'conf/bro/scripts/*'
  when: bro_custom_scripts == True

####################################################################
# BRO deploy
####################################################################
- name: Run Bro deploy
  command: '{{ bro_base }}/bin/broctl deploy'
  become: yes
  become_user: '{{ bro_user }}'

####################################################################
# Start Bro 
# Credit for service file: https://gist.github.com/JustinAzoff/db71b901b1070a88f2d72738bf212749
####################################################################
- name: Copy SystemD module
  template:
    src: conf/bro/bro.service
    dest: /etc/systemd/system/bro.service
    owner: root
    group: root
    mode: 0400

- name: Start Bro service
  service:
    name: bro
    state: restarted
    enabled: yes

####################################################################
#  Slack notification
####################################################################
- name: Send slack notification when done
  slack:
    token: "{{ slack_token }}"
    msg: '{{ ansible_nodename }}:{{ ansible_default_ipv4.address }} - Finished setting up Bro on {{ ansible_nodename }}'
    channel: "{{ slack_channel }}"
  when: slack_token != None