####################################################################
# Install/Setup Splunk Forwarder
####################################################################
- name: Copy Splunk Forwarder
  copy:
    src: files/splunk/splunkforwarder.deb
    dest: /tmp/splunkforwarder.deb

- name: Install Splunk from DEB
  apt:
    deb: /tmp/splunkforwarder.deb

- name: Copy splunk inputs.conf
  template:
    src: conf/splunk/forwarder/inputs.conf
    dest: /opt/splunkforwarder/etc/system/local/inputs.conf

- name: Copy splunk outputs.conf
  template:
    src: conf/splunk/forwarder/outputs.conf
    dest: /opt/splunkforwarder/etc/system/local/outputs.conf

- name: Copy Splunk Forwarder service
  template:
    src: conf/splunk/forwarder/splunk-forwarder.service
    dest: /etc/systemd/system/splunk-forwarder.service    

- name: Start Splunk forwarder
  systemd:
    name: 'splunk-forwarder'
    state: started
    enabled: yes
    daemon_reload: yes

- name: Disable HTTP server for forwarder
  lineinfile:
    path: /opt/splunkforwarder/etc/system/local/server.conf
    line: '{{ item }}'
  with_items:
    - "# Disable management port to prevent remote (or local) config."
    - "[httpServer]"
    - "disableDefaultPort = true"

- name: Start Splunk forwarder
  systemd:
    name: 'splunk-forwarder'
    state: restarted
    enabled: yes
    daemon_reload: yes
   

####################################################################
#  Slack notification
####################################################################
- name: Send slack notification when done
  slack:
    token: "{{ slack_token }}"
    msg: '{{ ansible_nodename }}:{{ ansible_default_ipv4.address }} - Finished setting up Splunk forwarder on BRO {{ ansible_nodename }}'
    channel: "{{ slack_channel }}"
  when: slack_token != None