version: '3.4'
services:
  mongo:
    image: mongo:3.6
    volumes:
      - caldera-mongo:/data/db
    command: 'mongod --bind_ip 0.0.0.0 --replSet caldera'
    networks: 
      - caldera-backend
  app:
    image: caldera
    ports:
      - 8888:8888
    depends_on:
      - db
    networks: 
      - caldera-backend
      - caldera-frontend

networks:
  - caldera-backend:
      driver: overlay
  - caldera-frontend:
      external: true
        driver: bridge

volumes:
  caldera-mongo: