####################################################################
# Create directories
####################################################################
- name: Create Splunk Docker directory
  file:
    path: '{{ docker_path }}/splunk'
    state: directory
    owner: root
    group: root
    mode: 0600

- name: Spin up Docker container
  docker_container:
    name: splunk
    image: splunk/splunk:7.2
    state: started
    restart_policy: unless-stopped
    ports:
      - 8000:8000
      - 9997:9997
    env:
      SPLUNK_START_ARGS=--accept-license
      SPLUNK_PASSWORD=changeme
    volumes:
      - '{{ docker_path }}/splunk/etc:/opt/splunk/etc'
      - '{{ docker_path }}/splunk/var:/opt/splunk/var'

####################################################################
#  Slack notification
####################################################################
- name: Send slack notification when done
  slack:
    token: "{{ slack_token }}"
    msg: '{{ ansible_nodename }}:{{ ansible_default_ipv4.address }} - Setup Splunk - {{ ansible_nodename }}'
    channel: "{{ slack_channel }}"
  when: slack_token != None