####################################################################
# Create directories
####################################################################
- name: Create Splunk Docker directory
  file:
    path: '{{ docker_path }}/splunk'
    state: directory
    owner: root
    group: root
    mode: 0600

- name: Create Splunk build directory
  file:
    path: '{{ docker_path }}/splunk/build'
    state: directory
    owner: root
    group: root
    mode: 0600

- name: Create Splunk Docker directory
  file:
    path: '{{ docker_path }}/splunk/certs'
    state: directory
    owner: root
    group: root
    mode: 0600

####################################################################
# Spin up NGINX for HTTPS
####################################################################
- name: Stat DH key
  stat:
    path: '{{ docker_path }}/splunk/certs/dhparam.pem'
  register: stat_dhparam

- name: Generate DH key
  shell: openssl dhparam -out {{ docker_path }}/splunk/certs/dhparam.pem 2048
  when: stat_dhparam.stat.exists == False

- name: Generate self signed cert
  shell: openssl req -new -nodes -x509 -days 3650 -subj "/C={{ cert_country }}/ST={{ cert_state }}/L={{ cert_local }}/O={{ cert_org }}/CN={{ hostname }}.{{ base_domain }}" -keyout {{ docker_path }}/splunk/certs/nginx-selfsigned.key -out {{ docker_path }}/splunk/certs/nginx-selfsigned.crt
  when: stat_dhparam.stat.exists == False

- name: Copy NGINX conf
  template:
    src: conf/splunk/nginx_splunk.conf
    dest: '{{ docker_path }}/splunk/nginx_splunk.conf'

####################################################################
# Spin up Splunk stack 
####################################################################
- name: Download Splunk docker-compose.yml
  template:
    src: roles/splunk/docker-compose.yml
    dest: '{{ docker_path }}/splunk/build/docker-compose.yml'

- name: Spin up Splunk
  docker_service:
    project_src: '{{ docker_path }}/splunk/build'
    project_name: splunkstack

####################################################################
#  Slack notification
####################################################################
- name: Send slack notification when done
  slack:
    token: "{{ slack_token }}"
    msg: '{{ ansible_nodename }}:{{ ansible_default_ipv4.address }} - Setup Splunk and NGINX - {{ ansible_nodename }}'
    channel: "{{ slack_channel }}"
  when: slack_token != None