- hosts: splunk
  become: yes
  become_user: root
  tasks:
    - include_vars: group_vars/docker.yml
    - include_vars: group_vars/logging.yml
    - import_tasks: roles/splunk/setup_splunk_container.yml
