- hosts: splunk
  become: yes
  become_user: root
  tasks:
    - include_vars: 'group_vars/sec_tools.yml'
    #- import_tasks: 'roles/docker/setup_docker.yml'
    - import_tasks: 'roles/splunk/setup_splunk_container.yml'
