FROM ubuntu:18.04 as zeek-build

ENV DEBIAN_FRONTEND noninteractive

# install prereqs
RUN apt-get update -y && apt-get install cmake make gcc g++ flex bison libpcap-dev libssl-dev python-dev swig zlib1g-dev git -y

# Download Zeek
RUN cd /tmp && git clone --recursive https://github.com/zeek/zeek

# Compile Zeek
RUN cd /tmp/zeek && \
    ./configure --prefix=/opt/bro/ && \
    make && \
    make install 

# Delete Zeek download
RUN rm -rf /tmp/zeek

FROM ubuntu:18.04 as zeek-standalone

# Build args
ARG zeek_interface=eth0

# Install 
RUN apt-get update -y && apt-get install wget net-tools supervisor vim libpcap-dev -y

# Copy Zeek from build
COPY --from=zeek-build /opt/bro /opt/bro

# Create scripts directory
RUN mkdir /opt/bro/share/bro/site

# Change default interface
RUN sed -i "s/interface=eth0/interface=$zeek_interface/g" /opt/bro/etc/node.cfg

# Supervisor
COPY conf/supervisor/supervisor.conf /etc/supervisor/conf.d/supervisord.conf

# Entrypoint
CMD ["/usr/bin/supervisord","-c","/etc/supervisor/conf.d/supervisord.conf"]